name: Code checks

on:
  push:
    branches:
      - dev

jobs:
  test-and-merge-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          ref: dev # Specify the branch to check out

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run pytest tests
        run: |
          python tests/test_train.py

      - name: Check test results and provide merge status
        run: |
          if [[ $? -eq 0 ]]; then
            echo "Ready to merge with main branch"
          else
            echo "Code changes need further attention"
          fi



