name: Deployment Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'            # Ignore changes to README.md
      - '.github/workflows/*'  # Ignore changes in the .github/workflows directory

jobs:
  Dev:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run dev script
        run: |
          python src/model/train.py

  Prod:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run production script
        run: |
          python src/model/train.py

      

           
    
